# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:

  pull_request:
    branches: ["dev"]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download deps
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn format

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download deps
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
